#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr

FEXT="BAK"
LIM=9
N=1

if (( $# != 1 )); then
	print -u2 "usage: ${0##*/} [file]"
	exit 1
elif [[ ! -f $1 ]]; then
	print -ru2 -- "$1 is missing!"
	exit 1
fi

while true; do
	if (( N > LIM )); then
		print -u2 "You reached the limit ($LIM .${FEXT} files)"
		exit 1
	fi
	if [[ ! -f ${1}.${FEXT}.${N} ]]; then
		cp -- "$1" "${1}.${FEXT}.${N}"
		print -r -- "$1 copied to ${1}.${FEXT}.${N}" 
		exit
	fi
	(( N++ ))
done

exit
