#!/usr/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>

if (( $# != 2 )); then
	print "Usage: ${0##*/} [archive_name] [filename]"
	exit 1
fi

function catar {
	if [[ -f $1 ]]; then
		case $1 in
			*.tar) tar -tf $1 $2 ;;
			*.tar.bz2) tar -jtf $1 $2 ;;
			*.tar.gz) tar -zxOf $1 $2 ;;
			*.tar.xz) tar -JxOf $1 $2 ;;
			*.tgz) tar -zxOf $1 $2 ;;
			*.rar) unrar p $1 $2 ;;
			*.zip) unzip -l $1 $2 ;;
			*) print "Unknown archive extension!" ; exit 1 ;;
		esac
	else
		print "Archive is missing!"
		exit 1
	fi
}

catar $1 $2
exit 0
