#!/bin/sh
# Script by Ypnose - http://ywstd.fr
# Remove trash files from Mac (.DS_Store), Windows (Thumbs.db) or KDE.

TRA="$(find . -type f -iname "Thumbs.db" -o -iname "desktop.ini" \
	-o -iname ".directory" -o -iname ".DS_Store")"

if [ -n "$TRA" ]; then
	find . -type f \( -iname "Thumbs.db" -o -iname "desktop.ini" \
		-o -iname ".directory" -o -iname ".DS_Store" \) -print0 | xargs -0 rm
	[ $? -eq 0 ] && printf "%s\n" "The file(s) found have been successfully deleted"
else
	printf "%s\n" "No file(s) has been detected!"
fi

exit
