#!/usr/bin/mksh
# Script by Ypnose - http://ypnose.org
# List folders sizes

function colorize {
	while IFS=$'\t' read -r SIZE FILDIR; do
		print -- "\033[1;35m${SIZE}\033[0m\t${FILDIR}"
	done
}

if [[ $1 = "-h" ]]; then
	print "usage: ${0##*/} [-h] [-r] directory"
	print "   -r   List the directory size recursively"
fi

if [[ -z $1 ]]; then
	du -sh ./*/ | colorize
	exit
fi

if [[ -d $1 ]]; then
	du -sh "$1" | colorize
	exit
fi

if (( $# == 2 )) && [[ $1 = "-r" ]]; then
	if (( $(du -h "$2" | wc -l) > 36 )); then
		du -h "$2" | colorize | less -R
	else
		du -h "$2" | colorize
	fi
	exit
fi

if [[ $1 = "-r" ]]; then
	if (( $(du -h "./" | wc -l) > 36 )); then
		du -h "./" | colorize | less -R
	else
		du -h "./" | colorize
	fi
	exit
fi

exit
