#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr

if [[ $1 = "-h" ]]; then
	print "usage: ${0##*/} [-h] [URL]"
	exit
elif [[ -z $1 ]]; then
	print -u2 "URL is missing"
	exit 1
fi

if [[ -n $(whence -p curl) ]]; then
	for f in "$@"; do
		curl -fOL --ipv4 -- "$f"
	done
elif [[ -n $(whence -p wget) ]]; then
	wget --inet4-only -- "$@"
else
	print -u2 "Unable to find curl / wget"
	exit 1
fi

exit
