#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr
# 4 Ultraviolent, 5 Nightmare. Previous skill levels are designed for milksops.
# Make sure your DOOM2.WAD is in $HOME/.prboom(-plus)

function usage {
	print "usage: doosh [-d WAD DIRECTORY] [-h] [-s SKILL LVL]"
	exit
}

function p_err {
	print -ru2 "ERROR: $1"
	exit 1
}

while getopts "d:hs:" opt; do
	case "$opt" in
		d) MLDIR="$OPTARG" ;;
		h) usage           ;;
		s) SKIW="$OPTARG"  ;;
		*) usage           ;;
	esac
done
shift $(( OPTIND - 1 ))

if [[ -z $MLDIR ]]; then
	p_err "WAD directory not specified"
elif [[ ! -d $MLDIR ]]; then
	p_err "$MLDIR is missing"
fi

if [[ -n $SKIW ]] && (( SKIW < 1 || SKIW > 5 )); then
	p_err "Wrong skill level"
fi

PS3='Choose the Master Levels WAD: '
select NAMW in ATTACK BLACKTWR BLOODSEA CANYON CATWALK COMBINE FISTULA \
	GARRISON GERYON MANOR MEPHISTO MINOS NESSUS PARADOX SUBSPACE SUBTERRA \
	TEETH TTRAP VESPERAS VIRGIL; do
	case $REPLY in
		1)  LVLW="01" ;;
		2)  LVLW="25" ;;
		3)  LVLW="07" ;;
		4)  LVLW="01" ;;
		5)  LVLW="01" ;;
		6)  LVLW="01" ;;
		7)  LVLW="01" ;;
		8)  LVLW="01" ;;
		9)  LVLW="08" ;;
		10) LVLW="01" ;;
		11) LVLW="07" ;;
		12) LVLW="05" ;;
		13) LVLW="07" ;;
		14) LVLW="01" ;;
		15) LVLW="01" ;;
		16) LVLW="01" ;;
		17) LVLW="31" ;; # 32 Secret Level
		18) LVLW="01" ;;
		19) LVLW="09" ;;
		20) LVLW="03" ;;
		*)  p_err "Wrong number" ;;
	esac
	if [[ -f "${MLDIR}/${NAMW}.WAD" ]]; then
		prboom -complevel 2 -iwad DOOM2.WAD -file "${MLDIR}/${NAMW}.WAD" \
			-warp "$LVLW" -skill "${SKIW:-4}"
	else
		p_err "${NAMW}.WAD is missing in $MLDIR"
	fi
done

exit
