#!/bin/sh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>

display_usage() { 
	printf "%s\n" "Usage: ${0##*/} [\e[0;32marguments\e[0m]"
	printf "%s\n" "  Arguments:"
	printf "%s\n" "     -d 	Shutdown the computer"
	printf "%s\n\n" "     -r 	Reboot the computer"
	}

if [ -z "$1" ] || [ "$1" = "-h" ]; then
	display_usage
	exit 1
fi 

if [ -n "$DISPLAY" ]; then
	printf "You must close \e[0;31m%s\e[0m before launching this \e[0;32m%s\e[0m!\n\n" "XServer" "command"
	exit
fi

case "$1" in
    -d)
      sudo shutdown -h now
      ;;
    -r)
      sudo shutdown -r now
      ;;
    ?)
      display_usage
      ;;
esac
exit 0

