#!/usr/bin/mksh
# Script by Ypnose - http://ypnose.org

TIME=3

function display_usage {
	print "Usage: ener [-h] [-s] [-r]"
}

function launch_cmds {
	[[ -n $(pgrep mocp) ]] && mocp -x
	sleep $TIME
}

if [[ -z $1 || $1 = "-h" ]]; then
	display_usage
	exit
fi

if [[ -n $DISPLAY ]]; then
	print -u2 "You must close X before launching this command"
	exit 1
fi

case $1 in
	-s)
		print "Closing in $TIME seconds..."
		launch_cmds
		sudo shutdown -h now
		;;
	-r)
		print "Restarting in $TIME seconds..."
		launch_cmds
		sudo shutdown -r now
		;;
	*)
		display_usage
		exit 1
		;;
esac
exit
