#!/usr/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>

SYSDEF=/usr/lib/systemd/system/getty@.service
SYSTF=/etc/systemd/system/getty@tty1.service

if [[ -f $SYSTF ]]; then
	if [[ -x /usr/bin/colordiff ]]; then
		colordiff -u "$SYSTF" "$SYSDEF"
	else
		diff -u "$SYSTF" "$SYSDEF"
	fi
else
	print "File doesn't exist!"
	exit 1
fi

exit 0
