#!/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   IMPORTANT!!! Do not spam it, because you'll reach API Rate Limit and you'll be banned!
#   You need bc calculator
#   TODO: Add Bitbucket support

SOFT=${0##*/}

function usage {
	print "Usage: $SOFT [-l] [USER] [REPOSITORY]"
	print  "   -l   List repos"
	print  "   USER -> Github user"
	print  "   REPOSITORY -> Repository owned by previous user"
}

if [[ -z $1 || $1 = -h ]]; then
	usage
	exit 1
elif [[ $1 = -l ]]; then
	CHX="$2"
	GITUSER="${CHX:=Ypnose}"
	curl -s https://api.github.com/users/$GITUSER/repos | awk '/"name"/ {gsub (/"|,/,""); print $2}'
	exit 0
fi

if (( $# == 2 )); then
	TEMPF=$(mktemp)
	curl -s https://api.github.com/repos/"$1"/"$2" -o "$TEMPF"
	GET=$(awk '/"size"/ {gsub (/,/,""); print $2}' "$TEMPF")
	NUMBR=$(awk '{while (gsub(/"size"/,""))x++} END{print x}' "$TEMPF")
	if [[ -n $GET ]]; then
			if (( $NUMBR != 1 )); then
				unset GET
				GET=$(curl -s https://api.github.com/repos/$1/$2 | awk '/"size"/ && x==0 {gsub (/,/,""); if(x=1) print $2;exit}')
			elif (( $GET >= 1024 )) && [[ -x /usr/bin/bc ]]; then
				TOT=$(print "scale=2; ${GET}/1024" | bc)
				print "\e[0;32m$TOT\e[0m Mb"
			fi
		print "\e[0;32m$GET\e[0m kB"
	else
		print "\e[0;31mGithub repository not found!\e[0m"
		exit 1
	fi
fi
exit 0
