#!/usr/bin/mksh
# Script by Ypnose  <linuxien[AT]legtux[DOT]org>
# IMPORTANT!!! Do not spam it, because you'll reach API Rate Limit and you'll be banned!

if [[ $1 = "-h" ]]; then
	print "Usage: gthsize [user] [repository]"
	exit
fi

if [[ -z $1 ]] || (( $# == 1 )); then
	CHX="$1"
	GITUSER="${CHX:=Ypnose}"
	curl -Ss https://api.github.com/users/$GITUSER/repos | awk '/"name"/ {gsub (/"|,/,""); print $2}'
	exit
elif (( $# == 2 )); then
	TEMPF=$(mktemp)
	curl -Ss "https://api.github.com/repos/${1}/${2}" -o "$TEMPF"
	GET=$(awk '/"size"/ {gsub (/,/,""); print $2}' "$TEMPF")
	NUMBR=$(awk '{while (gsub(/"size"/,""))x++} END{print x}' "$TEMPF")
	if [[ -n $GET ]]; then
		if (( NUMBR != 1 )); then
			unset GET
			GET=$(curl -s https://api.github.com/repos/$1/$2 | awk '/"size"/ && x==0 {gsub (/,/,""); if(x=1) print $2;exit}')
		fi
		print "$GET kB"
	else
		print "Github repository not found!"
		exit 1
	fi
fi
exit
