#!/bin/sh
# Script by Ypnose  <linuxien[AT]legtux[DOT]org>
# Submitted to Unigine devs and they accepted it
# http://oilrush-game.com/forum/index.php?/topic/2134-heaven-benchmark/
cd bin
ARCH=$(uname -m)
if [ "$ARCH" = x86 ]; then
	./launcher_x86 -config ../data/launcher/launcher.xml
elif [ "$ARCH" = x86_64 ]; then
	./launcher_x64 -config ../data/launcher/launcher.xml
else
	echo "The architecture is unknown. Heaven Benchmark is compatible with x86 / x86_64." >&2
	echo "The program will now close." >&2
fi
