#!/usr/bin/mksh
# Script by Ypnose - http://ypnose.org

#LD_LIBRARY_PATH=$HOME/.bin/lib $HOME/.HoN/hon-x86_64
#LD_PRELOAD=$HOME/.bin/lib/libXss.so.1 $HOME/.HoN/hon-x86_64

if [[ -z $(pgrep hon-x86_64) ]]; then
	$HOME/.HoN/hon-x86_64
else
	print -u2 "HoN is already running!"
	exit 1
fi

exit 0
