#!/bin/sh
# Script by Ypnose - http://ywstd.fr
set -e

SHF="bash_profile bashrc"
URL="https://raw.githubusercontent.com/Ypnose/dotfiles/master/"

rm -rf .bash_history .bash_logout .bash_profile .bashrc .inputrc
for f in $SHF; do
	curl "${URL}/${f}" -o "${HOME}/.${f}"
done

exit
