#!/usr/bin/mksh
# Script by Ypnose  <linuxien[AT]legtux[DOT]org>

WER=$(find -type f -iname "*.pkg.tar.xz" | wc -l)

if (( WER == 0 )); then
	print "No package(s) found"
	exit
fi

print "You have $WER packages in $PWD"
while true; do
	print -n "Would you like to list these packages ? [Y/n] "
	read RESP
	case $RESP in
		[Yy]*) find -type f -iname "*.pkg.tar.xz" -printf '%h => %f\n' | sort; exit;;
		[Nn]*) exit;;
		*) print -u2 "Please answer yes or no!";;
	esac
done
