#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr

if [[ $1 = "-h" ]]; then
	print "usage: ${0##*/} [-h] [package_extension]"
	exit
elif [[ -n $1 ]]; then
	EXT="$1"
fi

WER=$(find . -type f -iname "*.${EXT:-tgz}" | wc -l)
if (( WER == 0 )); then
	print "No package(s) found"
	exit
fi

print "You have $WER packages in $PWD"
while true; do
	print -n "Would you like to list these packages? [Y/n] "
	read RESP
	case $RESP in
		[Yy]*) find . -type f -iname "*.${EXT:-tgz}" | while IFS=$'\n' read -r PKG; do 
				DIRP="${PKG%/*}"; DIRP="${DIRP#*/}"; PKGN="${PKG##*/}"; print " $DIRP => $PKGN"; done | sort; exit ;;
		[Nn]*) exit ;;
		*) print -u2 "Please answer yes or no!" ;;
	esac
done
