#!/bin/sh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Find files or folders which don't have UNIX permissions

#Default UNIX permissions
FILE=644
DIR=755

#List folders or directories which don't have default UNIX permissions
if [ "$1" = -h ]; then
	printf "%s\n" "Usage: ${0##*/} [optarg]"
	printf "%s\n" "  Optarg:"
	printf "%s\n" "   -f			Search for files with different permissions (default)"
	printf "%s\n\n" "   -d			Search for directories with different permissions"
	exit 1
fi 

if [ -z "$1" ] || [ "$1" = -f ]; then
	if [ "$(find -type f ! -perm "$FILE" | wc -l)" = 0 ]; then
		printf "\e[0;32m%s\e[0m\n" "No matches found!"
	elif [ "$(find -type f ! -perm "$FILE" | wc -l)" -gt 30 ]; then
		find -type f ! -perm "$FILE" | less
	else
		find -type f ! -perm "$FILE"
	fi
	exit 0
fi

if [ "$1" = -d ]; then
	if [ "$(find -type d ! -perm "$DIR" | wc -l)" = 0 ]; then
		printf "\e[0;32m%s\e[0m\n" "No matches found!"
	elif [ "$(find -type d ! -perm "$DIR" | wc -l)" -gt 30 ]; then
		find -type d ! -perm "$DIR" | less
	else
		find -type d ! -perm "$DIR"
	fi
	exit 0
fi
