#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr
# List archive content

function listar {
	if [[ -f $1 ]]; then
		case $1 in
			*.tar) tar -tf "$1" ;;
			*.tar.bz2) tar -jtf "$1" ;;
			*.tar.gz) tar -ztf "$1" ;;
			*.tar.xz) tar -Jtf "$1" ;;
			*.tgz) tar -ztf "$1" ;;
			*.xz) xz -l "$1" ;;
			*.xbps) tar -Jtf "$1" ;;
			*.rar) bsdtar -tf "$1" ;;
			*.zip) bsdtar -tf "$1" ;;
			*) print -u2 "Unknown archive extension!" ; exit 1 ;;
		esac
	else
		print -u2 "File doesn't exist!"
	fi
}

if (( $(listar $1 | wc -l) > 40 )); then
	listar "$1" | less
else
	listar "$1"
fi

exit 0
