#!/usr/bin/mksh
# Script by Ypnose - http://ypnose.org

function check_page {
	if (( $1 > 1 )); then
		PAGE="$1"
	elif [[ $1 = "yesterday" ]]; then
		PAGE="2"
	else
		print -u2 "Page number is wrong!"
		exit 1
	fi
}

while getopts ":hp:s" opt; do
	case $opt in
	h) print "usage: ${0##*/} [-h] [-p page_number] [-s]"; exit ;;
	p) check_page "$OPTARG" ;;
	s) SAVE="1" ;;
	:) print -u2 "Option -$OPTARG needs an argument"; exit 1 ;;
	\?) print -u2 "This option is invalid -$OPTARG"; exit 1 ;;
	esac
done
shift $(( OPTIND - 1 ))

URL="$(curl -Ss "http://www.bonjourmadame.fr/${PAGE:+page/${PAGE}/}" \
	| sed -ne '/class="photo post"/,/class="navigation"/p' | sed '/img/!d;s/.*src="//g;s/".*//g')"
EXT="${URL##*.}"
TEMF="$(mktemp /tmp/madam.XXXXXXXXXX)"

if [[ $URL = "http://"* ]]; then
	curl -Ss "$URL" -o "$TEMF" && sxiv -g "1280x1024" "$TEMF"
	if (( SAVE == 1 )); then
		SUF="${TEMF##*/}"
		cp "$TEMF" "${HOME}/${SUF}.${EXT}"
	fi
	rm "$TEMF"
else
	print -u2 "Wrong URL format"
	exit 1
fi

exit
