#!/usr/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>

if (( $# != 2 )); then
	print "usage: massdiff [directory1] [directory2]"
fi

for f in "$1"/*; do
	if [[ -f $2/${f##*/} ]]; then
		diff -q "$f" "$2/${f##*/}"
	fi
done
exit
