#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr

if (( $# != 2 )); then
	print "usage: ${0##*/} [directory1] [directory2]"
	exit 1
fi

for f in "$1"/*; do
	if [[ -f $2/${f##*/} ]]; then
		diff -q "${f%/*}" "$2/${f##*/}"
	fi
done
exit
