#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr
# UNMAINTAINED

function chk_pkg {
	if [[ -f $1 ]]; then
		curl -s "$URLD" #-o "$1".NEW
	else
		curl -s "$URLD" #-o "$1"
	fi
}

if [[ -z $1 ]] || (( $# != 2 )); then
	print "Usage: ${0##*/} [package_name] [package_file]"
	exit 1
fi

URLM="https://projects.archlinux.org/svntogit/packages.git/plain/trunk/$2?h=packages/$1"
URLC="https://projects.archlinux.org/svntogit/community.git/plain/trunk/$2?h=packages/$1"

if (( $(curl -SIs $URLM | awk 'NR==1{print $2}') != 404 )); then
	URLD="$URLM"
	chk_pkg "$2"
else
	if (( $(curl -SIs $URLC | awk 'NR==1{print $2}') != 404 )); then
		URLD="$URLC"
		chk_pkg "$2"
	else
		print -u2 "Package or file not found!"
		exit 1
	fi
fi

exit
