#!/bin/sh
# Script by Ypnose - http://ywstd.fr
# Query PKGBUILD online
# UNMAINTAINED!!

# With bash
# LET="${2:0:2}"
LET="$(echo $2 | cut -c -2)"
AUR="https://aur.archlinux.org/packages/${LET}/${2}/PKGBUILD"
URLP="https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/${1}"
URLC="https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/${1}"

if [ -z "$1" ] || [ "$1" = "-h" ]; then
	printf "%s\n%s\n" "usage: ${0##*/} [-a] package" \
	"    -a    Search package on AUR."
	exit 1
fi

if [ "$1" = "-a" ] && [ "$#" -eq 2 ]; then
	printf "%s\n" "Searching on AUR..."
	if [ -z "$(curl -s $AUR | grep '404')" ]; then
		printf "\n%s\n" "$(curl -s $AUR)"
		exit
	else
		printf "%s\n" "Package not found on AUR!" >&2
		exit 1
	fi
fi

printf "%s\n" "Trying core / extra repo..."
if [ "$(curl -s $URLP | awk 'NR == 1 {print $1}')" != "<!DOCTYPE" ]; then
	printf "\n%s\n" "$(curl -s $URLP)"
	exit
else
	printf "%s\n%s\n" "Package not found in core / extra" \
	"Trying community repo..."
	if [ "$(curl -s $URLC | awk 'NR == 1 {print $1}')" != "<!DOCTYPE" ]; then
		printf "\n%s\n" "$(curl -s $URLC)"
		exit
	else
		printf "%s\n" "Package not found!" >&2
		exit 1
	fi
fi

exit 0
