#!/usr/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Generate "ready-to-write" Jekyll posts & pages.

DIR=/$HOME/Repos/JekyBlog

if [[ -z $1 || $1 = "-h" ]]; then
	print "Usage: ${0##*/} [-p page_name] [article_title]"
	print "    -p 	Create a new page instead of a new post/article"
	exit 1
fi

# Generate page
if (( $# == 2 )) && [[ $1 = "-p" ]]; then
	NEWFOL="$2"
	typeset -l NEWFOL
	mkdir -p "${DIR}/${NEWFOL}" && cd "${DIR}/${NEWFOL}"
	print "\033[0;33mYou may rename the folder!\033[0m"
	cat >> index.md <<- EOF
	---
	layout: page
	title: "$2"
	---
	EOF
	exit 0
fi

# Generate post
DAYDAT=$(date "+%Y-%m-%d")
MONDAT=$(date "+%B")
MONDATF=${MONDAT::1}
typeset -u MONDATF
MONDAT=${MONDAT:1:3}
NAME=${1// /-}
typeset -l NAME
ART="${DAYDAT}-${NAME}.md"

if [[ -d $DIR/_drafts ]]; then
	cd "${DIR}/_drafts"
	cat >> "${ART}" <<- EOF
	---
	layout: post
	title: "$1"
	date: $DAYDAT `date "+%H:%M:%S"`
	month: ${MONDATF}${MONDAT}
	description: 
	categories:
	---
	EOF
else
	print -u2 "\033[0;31mDirectory doesn't exist!\033[0m"
	exit 1
fi
exit 0
