#!/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Generate "ready-to-write" Jekyll posts & pages.

DIR=/mnt/public/REPOS/JekyBlog

if [[ -z $1 || $1 = -h ]]; then
	print "Usage: ${0##*/} [-p page_name]"
	print "    -p 	Create a new page instead of a new post/article"
	exit 1
fi

# Generate page
if (( $# == 2 )) && [[ $1 = -p ]]; then
	NEWFOL="$2"
	typeset -l NEWFOL
	mkdir -p "$DIR/$NEWFOL" && cd "$DIR/$NEWFOL"
	print "\033[0;33mYou may rename the folder!\033[0m"
	print "--" "---" > index.markdown
	print "layout: page" >> index.markdown
	print "title: \"$2\"" >> index.markdown
	print "--" "---" >> index.markdown
	exit 0
fi

# Generate post
TIMDAT=$(date "+%Y-%m-%d")
NAME=${1// /-}
typeset -l NAME
ART="$TIMDAT-$NAME.markdown"

if [[ -d $DIR/_posts ]]; then
	cd "$DIR/_posts"
	print "--" "---" > $ART
	print "layout: post" >> $ART
	print "title: \"$1\"" >> $ART
	print "date: $TIMDAT `date \"+%H:%M:%S\"`" >> $ART
	print "description: " >> $ART
	print "categories:" >> $ART
	print "--" "---" >> $ART
else
	print "\033[0;31mDirectory doesn't exist!\033[0m"
	exit 1
fi
exit 0
