#!/bin/sh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>

LOC=/mnt/public/REPOS
REPS=$(ls -d */)
DAT=$(date "+%d-%m-%Y")
#DIRD=/mnt/USB1/CONFSAVE
DIRD=$HOME/Documents
NUMBAR=$(find $DIRD -type f -iname "REPOS*.tar.gz" | wc -l)

cd $LOC
tar -czf "REPOS-$DAT.tar.gz" $REPS

if [ -n "$DIRD" ] && [ -d "$DIRD" ]; then
	if [ "$NUMBAR" -ge 3 ]; then
		FILAST=$(ls -1t $DIRD/REPOS* | tail -1)
		rm $FILAST
	fi
			mv "REPOS-$DAT.tar.gz" $DIRD
			printf "Saved archive in \e[0;32m%s\e[0m\n" "$DIRD"
	else
			printf "Saved archive in \e[0;32m%s\e[0m\n" "$LOC"
fi

exit 0
