#!/bin/bash
# Script by Ypnose  <linuxien[AT]legtux[DOT]org>
# This script saves core config files for Archlinux in the specified folder
# If you want to use it, you may change $DIRS and files accordingly!

DIR=$HOME/Documents
#DIR=/media/USB

if [[ -d "$DIR" ]]; then
	echo -e "\e[0;32mThe directory exists. It will be used for your configs.\e[0m"
	echo -e "\e[0;33mStarting backup...\e[0m"
	else
	echo -e "\e[0;31mThe directory does not exist. You should change DIR location!\e[0m"
	exit
fi

DAT=$(date "+%d-%m-%Y")
NEWFOL="$DIR/CONFS-$DAT"

# With -o argument, it overrides an existing folder
if [[ -d "$NEWFOL" && "$1" = "-o" ]]; then
	rm -R "$NEWFOL"
	echo -e "\e[0;31mOverwriting the existing folder!\e[0m"
fi

if [[ -d "$NEWFOL" ]]; then
	echo -e "\e[0;31mWARNING: You already synchronised your files today!\e[0m"
	exit
	else
	mkdir -p "$NEWFOL"
fi

#Filesystem
BOOTF="/boot/syslinux/syslinux.cfg"
ETCF="/etc/fstab /etc/issue /etc/locale.conf /etc/mkinitcpio.conf /etc/mkinitcpio-custom.conf /etc/nanorc /etc/wpa_supplicant.conf"
PACF="/etc/pacman.conf /etc/pacman.d/mirrorlist"
NETF="/etc/network.d/Madbox /etc/conf.d/netcfg"
MODF="/etc/modprobe.d/modprobe.conf"
XORGF="/etc/X11/xorg.conf.d/10-keyboard.conf /etc/X11/xorg.conf.d/10-nvidia.conf"
NANF="/usr/share/nano/conf.nanorc /usr/share/nano/pkgbuild.nanorc"
#User
BASHF="$HOME/.bashrc $HOME/.bash_profile"
MISCF="$HOME/.Xresources $HOME/.dir_colors $HOME/.gitconfig $HOME/.xinitrc $HOME/OUT.out $HOME/.config/user-dirs.conf $HOME/.config/fontconfig/fonts.conf"
FIREF=$(find -type d -iname "*.default")

#Option: comment $OPTF if you don't need it.
OPTF="$HOME/.bin/ $HOME/.fonts/ $HOME/.moc/themes/ $HOME/.themes/ $HOME/Builds/ $HOME/Documents/Font/ $HOME/Documents/Pics/ $HOME/Documents/bookmarks.html $HOME/Documents/Certificate_Mad.p12"

#Message
echo -e "\e[0;33mThe following files will be copied\e[0m => $BOOTF $ETCF $PACF $NETF $MODF $XORGF $NANF $BASHF $MISCF"

if [[ -n $FIREF ]]; then
	cp -r $FIREF/searchplugins/ $NEWFOL
	cp $FIREF/prefs.js $NEWFOL
else
	echo -e "\e[0;31mNo Firefox profile found!\e[0m"
fi

#Copy core files
for FILES in "$BOOTF $ETCF $PACF $NETF $MODF $XORGF $NANF $BASHF $MISCF"
	do
		echo -e "\e[0;33m"
		cp -v $FILES $NEWFOL
done

#Packages list
echo -e "$DAT\n" > $NEWFOL/pacman_pkgs.out
pacman -Q >> $NEWFOL/pacman_pkgs.out

#Option
if [[ -n "$OPTF" ]]; then
	echo -e "\e[0mOptional files will be saved!"
	mkdir -p $NEWFOL/OPT
	cp -r --preserve=links $OPTF $NEWFOL/OPT
	else
	echo -e "\e[0mNo optional files defined!"
fi

echo -e "\n\e[0mYou saved $(ls -A $NEWFOL | wc -l) files"
echo -e "\e[0;32mDone.\e[0m"
exit
