#!/bin/bash
# Script by Ypnose  <linuxien[AT]legtux[DOT]org>
# This script saves core config files for Archlinux in the specified folder
# If you want to use it, you may change $DIRS and files accordingly!

TARGZ=n
DIR=$HOME/Documents
#DIR=/mnt/USB1

usage() {
	echo "Usage: ${0##*/} [OPTARG]"
	echo "  OPTARG:"
	echo -e "    -o 	Overwrite existing tar.gz archive or directory\n"
}

if [[ "$1" = -h ]]; then
	usage
	exit
fi 

if [[ -d "$DIR" ]]; then
	echo -e "\e[0;32mThe directory exists. It will be used for your configs.\e[0m"
	echo -e "\e[0;33mStarting backup...\e[0m"
	else
	echo -e "\e[0;31mThe directory does not exist. You should change DIR location!\e[0m"
	exit
fi

DAT=$(date "+%d-%m-%Y")
NEWFOL="$DIR/CONFS-$DAT"

# With -o argument, it overrides an existing folder / archive
if [[ -d "$NEWFOL" && "$1" = "-o" ]]; then
	echo -e "\e[0;31mOverwriting the existing folder!\e[0m"
	rm -R "$NEWFOL"
fi

if [[ -e "$DIR/CONFS-$DAT.tar.gz" && "$1" = "-o" ]]; then
	echo -e "\e[0;31mOverwriting the existing archive!\e[0m"
	rm "$DIR/CONFS-$DAT.tar.gz"
fi

if [[ -d "$NEWFOL" || -e "$DIR/CONFS-$DAT.tar.gz" ]]; then
	echo -e "\e[0;31mWARNING: You already synchronised your files today!\e[0m"
	exit
	else
	mkdir -p "$NEWFOL"
fi

#-------------------------------------
#Filesystem
BOOTF="/boot/syslinux/syslinux.cfg"
ETCF="/etc/fstab /etc/issue /etc/locale.conf /etc/mkinitcpio.conf /etc/mkinitcpio-custom.conf /etc/nanorc /etc/wpa_supplicant.conf"
PACF="/etc/pacman.conf /etc/pacman.d/mirrorlist"
NETF="/etc/network.d/Madbox /etc/conf.d/netcfg"
MODF="/etc/modprobe.d/modprobe.conf"
XORGF="/etc/X11/xorg.conf.d/10-keyboard.conf /etc/X11/xorg.conf.d/20-nvidia.conf"
NANF="/usr/share/nano/conf.nanorc /usr/share/nano/pkgbuild.nanorc"
#User
BASHF="$HOME/.bashrc $HOME/.bash_profile"
MISCF="$HOME/.Xresources $HOME/.dir_colors $HOME/.gitconfig $HOME/.xinitrc $HOME/OUT.out $HOME/.config/user-dirs.conf $HOME/.config/fontconfig/fonts.conf"
FIREF=$(find $HOME -type d -iname "*.default")

#Option: comment $OPTF if you don't need it.
OPTF="$HOME/.bin/ $HOME/.config/geany/colorschemes/ $HOME/.fonts/ $HOME/.moc/themes/ $HOME/.themes/ $HOME/Documents/Font/ $HOME/Documents/Pics/ $HOME/Documents/bookmarks.html $HOME/Documents/Certificate_Mad.p12"
SHF=".ssh/"
ARCF="Builds"
#-------------------------------------

#Message
echo -e "\e[0;33mThe following files will be copied\e[0m => $BOOTF $ETCF $PACF $NETF $MODF $XORGF $NANF $BASHF $MISCF"

#Copy core files
for FILES in "$BOOTF $ETCF $PACF $NETF $MODF $XORGF $NANF $BASHF $MISCF"
	do
		echo -e "\e[0;33m"
		cp -v $FILES $NEWFOL
done

if [[ -n $FIREF && -d $FIREF/searchplugins ]]; then
	cp -r $FIREF/searchplugins $NEWFOL
	cp $FIREF/prefs.js $NEWFOL
	else
	echo -e "\n\e[0;31mNo Firefox profile found!\e[0m"
fi

#Packages list
echo -e "$DAT\n" > $NEWFOL/pacman_pkgs.out
pacman -Q >> $NEWFOL/pacman_pkgs.out
echo -e "\n$(pacman -Q | wc -l) packages" >> $NEWFOL/pacman_pkgs.out

#Option
if [[ -n "$OPTF" ]]; then
	echo -e "\n\e[0mOptional files will be saved!"
	mkdir -p $NEWFOL/OPT
	cp -r $OPTF $NEWFOL/OPT
	else
	echo -e "\e[0mNo optional files defined!"
fi

if [[ -n "$SHF" ]]; then
	cd $HOME
	tar -czf $NEWFOL/OPT/SSH.tar.gz $SHF
fi

if [[ -n "$ARCF" && -d "$HOME/Builds" ]]; then
	cd $HOME
	tar -czf $NEWFOL/Builds.tar.gz $ARCF
fi

echo -e "\n\e[0mThe script saved $(find $NEWFOL -type f | wc -l) files\n"

if [[ "$TARGZ" = yes || "$TARGZ" = y ]]; then
	cd $DIR
	tar -czf "CONFS-$DAT".tar.gz "CONFS-$DAT"
	echo -e "\e[0;32mArchive has been successfully created"
	rm -R $NEWFOL
	else
	echo -e "\e[0;33mArchive option turned off!\e[0m"
fi

echo -e "\e[0;32mDone.\e[0m"
exit
