#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr
set -e

trap '[[ -f $TPFILE ]] && rm "$TPFILE"' INT EXIT

TPFILE="$(mktemp /tmp/${0##*/}.XXXXXXXXXX)"
URLGIT="https://raw.githubusercontent.com/Ypnose/scripts/master"

if [[ ! -f ${PWD}/CHKLIST ]]; then
	print -u2 "Unable to find CHKLIST in $PWD"
	exit 1
fi

while IFS=$'\n' read -r SCR; do
	[[ -z $SCR || ${SCR:0:1} = "#" ]] && continue
	# Replace shebang (set mksh path with $1?)
	wget -q --inet4-only -O - "${URLGIT}/${SCR}" \
		| sed '1 s|/usr/bin/mksh$|/bin/mksh|' >"$TPFILE"
	# Test changes on existing file
	if [[ -f ${PWD}/${SCR} && -z $(diff -q "${PWD}/${SCR}" "$TPFILE") ]]; then
		continue
	fi
	# Test if the new file isn't empty
	if [[ -s $TPFILE ]]; then
		cp "$TPFILE" "${PWD}/${SCR}"
		chmod +x "${PWD}/${SCR}"
	fi
done <"${PWD}/CHKLIST"

exit
