#!/usr/bin/mksh
# Script by Ypnose - http://ywstd.fr
# UNMAINTAINED

if [[ -n $(pgrep jekyll) ]]; then
	print -u2 "ERROR: Jekyll already running!"
	exit 1
fi

if [[ $PWD != "$HOME/Repos/JekyBlog" ]]; then
	cd "$HOME/Repos/JekyBlog"
	jekyll serve --watch
else
	jekyll serve --watch
fi
exit
