#!/usr/bin/mksh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Remove existing pkg / src folders

function ask {
	while true; do
		print "Do you want to delete $DIR ? [Y/n] "
		read -r yn
		case $yn in
			[Yy])
					print "\e[0;31mDeleting $DIR directory!\e[0m"
					rm -r "$DIR"
					break
					;;
			[Nn])
					break
					;;
			*)
					print "Please answer yes or no!"
					;;
		esac
	done
}

if [[ -d pkg ]]; then
	DIR=pkg
	print "\e[0;33m[=> $DIR directory exists\e[0m"
	ask
else
	print "\e[0;32mDirectory pkg not found!\e[0m"
fi
if [[ -d src ]]; then
	DIR=src
	print "\e[0;33m[=> $DIR directory exists\e[0m"
	ask
else
	print "\e[0;32mDirectory src not found!\e[0m"
fi

exit 0
