#!/bin/sh
# Script by Ypnose - http://ywstd.fr

HDP=$(sudo hdparm -I /dev/sda | awk '/Advanced power/{print $5}')
PWM="/sys/class/drm/card0/device/power_method"
PWP="/sys/class/drm/card0/device/power_profile"
HDPV="254"
PWMV="profile"
PWPV="low"

if [ -x "/sbin/hdparm" ]; then
	if [ "$HDP" = "$HDPV" ]; then
		printf "%d\n" "$HDP"
	else
		printf "%s\n" "Value is not $HDPV" >&2
	fi
else
	printf "%s\n" "Hdparm is not installed!" >&2
fi
if [ -f "$PWM" ]; then
	if [ "$(cat $PWM)" = "$PWMV" ]; then
		cat "$PWM"
	else
		printf "%s\n" "Value is not $PWMV" >&2
	fi
else
	printf "%s\n" "$PWM is missing" >&2
fi
if [ -f "$PWP" ]; then
	if [ "$(cat $PWP)" = "$PWPV" ]; then
		cat "$PWP"
	else
		printf "%s\n" "Value is not $PWPV" >&2
	fi
else
	printf "%s\n" "$PWP is missing" >&2
fi
exit
