#!/bin/sh
# Script by Ypnose - http://ywstd.fr

if [ "$#" -ne 2 ]; then
	printf "%s\n" "Usage: ${0##*/} <movie_file> <subtitles_file.srt>"
	exit 1
elif [ ! -f "$2" ]; then
	printf "%s\n" "$2 doesn't exist!" >&2
	exit 1
fi

MOVNAM="${1%.*}"
MOVEXT="${1##*.}"
# Works with bash
# MOVFIL="${MOVNAM//./-}"
MOVFIL="$(echo $MOVNAM | sed 's/\./-/g')"

if [ "$MOVNAM" != "${MOVNAM%.*}" ]; then
	mv "$MOVNAM"."$MOVEXT" "$MOVFIL"."$MOVEXT"
fi

if [ "${2##*.}" = "srt" ]; then
	mv "$2" "$MOVFIL".srt
	printf "%s\n" "Done"
else
	printf "%s\n" "Wrong file extension!" >&2
	exit 1
fi
exit
