#!/bin/sh
# Based on those lines: http://linuxwireless.org/en/users/Drivers/b43#Other_distributions_not_mentioned_above

FIRMWARE_INSTALL_DIR="/lib/firmware"

wget http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2
tar xjf broadcom-wl-5.100.138.tar.bz2
sudo b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" broadcom-wl-5.100.138/linux/wl_apsta.o

# UNIX folder permissions
sudo chmod 755 "$FIRMWARE_INSTALL_DIR"/b43

exit
