#!/bin/sh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Based on those lines: http://linuxwireless.org/en/users/Drivers/b43#Other_distributions_not_mentioned_above

FIRMWARE_INSTALL_DIR="/lib/firmware"
URL="http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2"

dlfirm() {
	if [ -x "/usr/bin/curl" ]; then
		curl -O "$URL"
	elif [ -x "/usr/bin/wget" ]; then
		wget "$URL"
	fi
}

extfirm() {
	tar xjf broadcom-wl-5.100.138.tar.bz2
	sudo b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" broadcom-wl-5.100.138/linux/wl_apsta.o
	# UNIX folder permissions
	sudo chmod 755 "$FIRMWARE_INSTALL_DIR"/b43
}

if [ "$1" = "-d" ]; then
	dlfirm
	exit 0
elif [ "$1" = "-e" ]; then
	extfirm
	exit 0
fi

dlfirm
extfirm

exit 0
