#!/bin/sh
# Script by Ypnose - http://ypnose.org
# Based on those lines: http://linuxwireless.org/en/users/Drivers/b43#Other_distributions_not_mentioned_above

FIRMWARE_INSTALL_DIR="/lib/firmware"
URL="http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2"

dlfirm() {
	if [ -f "${URL##*/}" ]; then
		printf "%s\n" "An existing archive has been already downloaded!" >&2
		exit 1
	fi
	if [ -x "/usr/bin/curl" ]; then
		curl -O "$URL"
	elif [ -x "/usr/bin/wget" ]; then
		wget "$URL"
	fi
}

extfirm() {
	printf "%s\n" "Installing firmware..."
	tar xjf "${URL##*/}"
	sudo b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" broadcom-wl-5.100.138/linux/wl_apsta.o
	# UNIX folder permissions
	sudo chmod 755 ${FIRMWARE_INSTALL_DIR}/b43
}

case "$1" in
	-d) dlfirm; exit 0 ;;
	-e) extfirm; exit 0 ;;
	*) dlfirm; extfirm; exit ;;
esac
