#!/usr/bin/mksh
# Script by Ypnose - http://ypnose.org

if (( $# == 2 )); then
	diff -u "$@" | while IFS= read -r LINE; do
		CHAR="${LINE::1}"
		case $CHAR in
			\-) print -- "\033[1;31m${LINE}\033[0m" ;;
			\+) print -- "\033[0;32m${LINE}\033[0m" ;;
			\@) print -- "\033[1;35m${LINE}\033[0m" ;;
			*) print -- "$LINE" ;;
		esac
	done
else
	print -u2 "usage: ${0##*/} file1 file2"
fi

exit
