#!/usr/bin/awk -f
# Script by Ypnose - http://ypnose.org

BEGIN {FS="\n"}
symb=substr($0,1,1){
	if(symb~/\@/){
		print "\033[1;35m"$0"\033[0m"
	}else if(symb~/\-/){
		print "\033[1;31m"$0"\033[0m"
	}else if(symb~/\+/){
		print "\033[0;32m"$0"\033[0m"
	}else{
		print $0
	}
}

exit
